apiVersion: v1
kind: Service
metadata:
  name: story-service
spec:
  selector: 
    app: story
    #type helps it to get exposed externally
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000